### ISSUE TITLE
"User approval" feature

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#104]
This would make a cool checklist feature.

You could select certain users would then need to give the post a green checkmark

> I have a scenario I'd like to check with you, if possible with your plugin:
> I have a wikipedia site for movies, ie, each movie page with many fields (director, producer, actors etc).
> A user (let's say, the director) creates a movie page and adds its data. He then sends a message to 3 other people to come to the page and confirm the data (with a notification?).
> When all four people have confirmed the data (by flagging?) the page can be published.

**Comment by stevejburge** [comment]
One more request for this from a university customer. They have several specific tasks that they really need completed by certain users

**Comment by andergmartins** [comment]
New mockup to clarify the requirements:

<img width="1276" alt="Screen Shot 2020-08-04 at 13 08 33" src="https://user-images.githubusercontent.com/407131/89317537-de64d080-d653-11ea-8b4f-1aac38b4610f.png">

**Comment by stevejburge** [comment]
@andergmartins @olatechpro 

Sorry for causing confusion.

I think user role is enough. That also matches the "Who can ignore this task?" column

**Comment by andergmartins** [comment]
That's ok @stevejburge, thanks for clarifying. Ok, makes sense to me keep it simple for now.
