### ISSUE TITLE
"Hide Publish Button" not working 100% on Gutenberg

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#120]
The "Hide Publish Button" process don't work very smoothly in Gutenberg.

First, you can see the main "Publish" button, which is little confusing:

<img width="377" alt="first-publish" src="https://user-images.githubusercontent.com/3868028/72563366-84e5b180-387b-11ea-9375-eef75b55d153.png">

Then, you can not see the second "Publish" button but no reason is given about what's wrong:
<img width="302" alt="second-publish" src="https://user-images.githubusercontent.com/3868028/72563372-88793880-387b-11ea-8afd-3e9ce2e75b1b.png">

**Comment by stevejburge** [comment]
One confirming report of this from a customer today

**Comment by andergmartins** [comment]
We removed this feature due to incompatibility with Gutenberg, so I'm closing this issue.
