### ISSUE TITLE
Confusing text: "Are you sure you want to publish anyway?"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#124]
> the text in pre-publish Checklist block "Are you sure you want to publish anyway?" may be confusing, as the user cannot publish without rectifying the item.

**Comment by andergmartins** [comment]
If we have undone required tasks in the checklist the warning asks if we are sure we want to publish. But considering those are required tasks, it should not ask, but just inform. Maybe we could use the same message style we have when using the classic editor?

Here is the current message:

<img width="293" alt="Screen Shot 2020-03-25 at 19 19 36" src="https://user-images.githubusercontent.com/407131/77591000-cd4dcb00-6ecd-11ea-8833-089d0ba7afc9.png">

**Comment by andergmartins** [comment]
The classic editor use this message:

<img width="710" alt="Screen Shot 2020-03-26 at 10 17 18" src="https://user-images.githubusercontent.com/407131/77651047-ff514280-6f4a-11ea-9440-7b9104a36659.png">

**Comment by andergmartins** [comment]
New message when we have both required and recommended tasks:

<img width="291" alt="Screen Shot 2020-03-26 at 12 51 59" src="https://user-images.githubusercontent.com/407131/77667237-b1473980-6f60-11ea-8617-7d91bfe8af65.png">

New message when we have only recommended tasks:

<img width="284" alt="Screen Shot 2020-03-26 at 12 52 16" src="https://user-images.githubusercontent.com/407131/77667262-b86e4780-6f60-11ea-9916-1a7111b9a6d1.png">
