### ISSUE TITLE
Possible UI improvements for the extra items on a checklist

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#126]
> When you add a custom item on a checklist, it appears with a red X surrounded by a grey box. It would be more intuitive to have just the grey box without the red X and keep the red text to indicate it needs attention. That will make it look more like a control that can be clicked/checked and then have the green check mark appear and the text turn green when it's selected. 

<img width="257" alt="2020-02-19 12_56_52-Edit Post ‹ City of Bellingham — WordPress" src="https://user-images.githubusercontent.com/3868028/75045469-45823480-54bb-11ea-8a8f-2191fd22dd7d.png">
<img width="253" alt="2020-02-19 12_58_19-Edit Post ‹ City of Bellingham — WordPress" src="https://user-images.githubusercontent.com/3868028/75045475-461acb00-54bb-11ea-9667-53e1ec6e28de.png">
<img width="254" alt="2020-02-19 12_59_03-Edit Post ‹ City of Bellingham — WordPress" src="https://user-images.githubusercontent.com/3868028/75045477-46b36180-54bb-11ea-87df-c57430f17b57.png">

**Comment by stevejburge** [comment]
There was a 2nd piece of feedback for these same items:

>  The only other thing that was bit confusing is you can only select the check boxes on the sidebar metabox presentation. When you get to the Publish panel, it's a "read only" experience for the checklist items. It might be useful to make the manual check items checkable as well on that panel just prior to publishing.

**Comment by andergmartins** [comment]
Great suggestions 👍 I agree with both.
