### ISSUE TITLE
Horizontal tabs for checklists won't scale

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#127]
I don't think these horizontal tabs will scale very well for multiple post types:
<img width="895" alt="Screen Shot 2020-02-21 at 10 19 43 PM" src="https://user-images.githubusercontent.com/3868028/75076533-5735fd00-54f8-11ea-9f6f-26f180afc9fd.png">

Those all show, even though checklists aren't enabled for them:
<img width="409" alt="Screen Shot 2020-02-21 at 10 22 17 PM" src="https://user-images.githubusercontent.com/3868028/75076644-abd97800-54f8-11ea-850d-59b28b56b8e3.png">

How do we scale this when we really allow people to get flexible with checklists?

**Comment by andergmartins** [comment]
We have a few options:

1. Use a vertical list of post types (use an additional column, reducing horizontal space for the tasks and options
2. Use a select field with the list of post types. Selecting a post type refreshes the list of tasks respectively
3. Split in two screens: List of post types (like the list of posts) and checklist (like the post edit page).

For now, the 3rd option looks better to me. It fits well in the common WordPress UI, and open more room for additional configurations to the checklist. There could be a metabox for permissions and other configurations.

**Comment by stevejburge** [comment]
Thanks @andergmartins Yes, I think I agree with you on 3.

Maybe just show the checklists in a table like the Posts screen or our own PublishPress Authors?

<img width="819" alt="Screen Shot 2020-03-02 at 4 42 21 PM" src="https://user-images.githubusercontent.com/3868028/75720594-ceac1f00-5ca4-11ea-90c0-c70079dde86d.png">

**Comment by andergmartins** [comment]
For now we decided to fix this making sure to only display tabs for the enabled post types.

**Comment by small-fork** [comment]
Hello. I was instructed by Steve to add a screenshot here from my Checklists settings showing the predicted issue with overlapping tabs.
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/27249070/77585064-df217500-6eb1-11ea-936f-59d2362a3c35.png">

Let me know if any additional information would be helpful!

**Comment by stevejburge** [comment]
Thanks @small-fork, that's very helpful. 

Hopefully our next release will fix this.
