### ISSUE TITLE
Remove "Excerpt has text" task from "Page" checklist

### ISSUE THREAD

**Issue by VadymMalinovskyi** [publishpress/PublishPress-Checklists#128]
**Is your feature request related to a problem? Please describe.**
While adding new page there is no option to write excerpt. 

**Describe the solution you'd like**
My recommendation is to remove this task from checklist option for "Page" because it is useless. 

**Describe alternatives you've considered**

**Additional context**
<img width="266" alt="Снимок экрана 2020-03-16 в 15 14 52" src="https://user-images.githubusercontent.com/55210526/76804191-ea312280-6798-11ea-8209-d8ed2396ad63.png">

**Comment by andergmartins** [comment]
Thanks for reporting that, @VadymMalinovskyi.
We are going to remove it in a next release.
