### ISSUE TITLE
Disable the Quick Edit dropdown

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#151]
Ooops ... this is a very easy way to avoid the Checklist requirements:
<img width="515" alt="Screen Shot 2020-06-30 at 5 41 52 PM" src="https://user-images.githubusercontent.com/3868028/86179927-28104780-baf9-11ea-9f7f-c83399ed4d64.png">

**Comment by andergmartins** [comment]
Good catch. But maybe we should add that disabled by default, but provide a setting field to unhide it?

**Comment by stevejburge** [comment]
Yes, a setting is the best option
