### ISSUE TITLE
Add title for checklist tasks options in the checklists page to make clear what is the unity for counting the limit

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Checklists#155]
Right now we have only the min and max fields. But some tasks use that limit for words, other for chars. We need to make it clear what is the specific unity used for counting.

<img width="1281" alt="Screen Shot 2020-07-15 at 02 01 43" src="https://user-images.githubusercontent.com/407131/87505671-cf37c780-c63f-11ea-978d-5a561106f286.png">

**Comment by stevejburge** [comment]
@andergmartins Yes, you're right. Maybe the "Disabled, Recommended, Required" box should be made smaller to make room

We could put the longer explanations (for example) "Show in the sidebar and before publishing", in the footer

**Comment by andergmartins** [comment]
Maybe this is not required anymore. We changed the task name for v2.2.0 so it is more clear now:

<img width="1282" alt="Screen Shot 2020-07-21 at 14 05 02" src="https://user-images.githubusercontent.com/407131/88084823-5662cf00-cb5b-11ea-9557-fab9eab0c7df.png">

**Comment by stevejburge** [comment]
Agreed, we can close this
