### ISSUE TITLE
Simplify the text on options for "Disabled, Recommended or Required" on checklists

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Checklists#162]
> "Disabled, Recommended, Required" box should be made smaller to make room
> We could put the longer explanations (for example) "Show in the sidebar and before publishing", in the footer

Related to #155.

**Comment by stevejburge** [comment]
Maybe we can remove one of the two "Recommended" options and just have one.

**Comment by andergmartins** [comment]
Agreed. We probably could keep the one that shows in the sidebar and before publishing.
So we have:

* Disabled
* Recommended
* Required

And in the footer we add some help text as you suggested.
