### ISSUE TITLE
Hide Yoast SEO options if the plugin is not installed

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Checklists#164]
<img width="1123" alt="Screen Shot 2020-07-21 at 14 14 41" src="https://user-images.githubusercontent.com/407131/88085722-9ecebc80-cb5c-11ea-9b13-ab13db45bc94.png">

**Comment by olatechpro** [comment]
Hi @andergmartins. How do you prefer this to be done. Should i prevent the module from been loaded if Yoast SEO plugin does not exist(which means the options won't be available at all) or i should just disable the input in checklist ?

**Comment by olatechpro** [comment]
@andergmartins, i still await your response on this

**Comment by stevejburge** [comment]
@olatechpro Let's just hide it for now, if Yoast is not installed

**Comment by andergmartins** [comment]
@olatechpro sorry, missed your messages. I see the PR, I will review it today. 
Thanks
