### ISSUE TITLE
Validation for Required tasks

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#175]
At the moment, you can save a task as "Required" even if any Min and Max fields are empty. We should validate that these fields are used if the "Recommended" or "Required" fields are being used:
<img width="1294" alt="Screen Shot 2020-07-27 at 12 19 46 PM" src="https://user-images.githubusercontent.com/3868028/88566426-f9a46000-d003-11ea-8912-592e551b43e1.png">

**Comment by andergmartins** [comment]
Kind of a form validation here makes a lot of sense here 👍
