### ISSUE TITLE
Post type tabs don't work

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#197]
These tabs are not clickable in 5.5

![Screen Shot 2020-08-12 at 5 23 40 PM](https://user-images.githubusercontent.com/3868028/90069725-b4995280-dcc0-11ea-8bb1-bf03b7644a3f.png)

<img width="593" alt="Screen Shot 2020-08-12 at 5 25 45 PM" src="https://user-images.githubusercontent.com/3868028/90069839-deeb1000-dcc0-11ea-9dc2-ad03b7082e55.png">

**Comment by andergmartins** [comment]
Note to self: 
<img width="1279" alt="Screen Shot 2020-08-12 at 22 58 34" src="https://user-images.githubusercontent.com/407131/90085877-664f7800-dcef-11ea-9945-38d5bf64d91f.png">
