### ISSUE TITLE
Hide task not supported for post type

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#199]
This isn't needed:
![Screen Shot 2020-08-13 at 10 11 01 AM](https://user-images.githubusercontent.com/3868028/90144902-62ead980-dd4d-11ea-91b8-7d0e234078ed.png)

**Comment by ojopaul** [comment]
This issue should be updated to "Hide task not supported for post type" as the implementation fix apply to all post type, not just pages.

I would have update it but i'm not seeing edit icon/button on this repository

@stevejburge @andergmartins

**Comment by stevejburge** [comment]
@ojopaul try again now

**Comment by ojopaul** [comment]
All good now, so you can ignore my second comment on the PR i just opened
