### ISSUE TITLE
Trigger checklist validation for for Drafts and other statuses

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Checklists#221]
Right now we only validate the checklist state when the user tries to publish the post. We could give the option to run the verification for other statuses. So if the user clicks on "Save as Draft" we would validate the list and block it or display the warnings the same way we do for before publishing.

**Comment by stevejburge** [comment]
Closing in favor of https://github.com/publishpress/PublishPress-Checklists/issues/221
