### ISSUE TITLE
UI changes for the approval feature in the 2.4.0 release

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#222]
For user approval option, I don't think it can be hidden under "Add custom task". We should make it easily visible. If we do that, we can also drop the "Editable by" text

<img width="1239" alt="Screen Shot 2020-09-10 at 2 03 56 PM" src="https://user-images.githubusercontent.com/3868028/92777780-874acd80-f36e-11ea-9d0d-89e3d2badea0.png">

**Comment by andergmartins** [comment]
Ok, we will add it as a normal task with the text: "Approved by a user in this role" but still keep the "Editable by" field for custom tasks, so users can have more than one "approved by" if needed.
