### ISSUE TITLE
Small text and UI changes for 2.4.0

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#223]
- "Validate links format" should be "All links use a valid format". Let's also move it up next to the other link options:

<img width="270" alt="Screen Shot 2020-09-10 at 2 09 06 PM" src="https://user-images.githubusercontent.com/3868028/92778614-561ecd00-f36f-11ea-8abc-9accfe64cfff.png">

- Yoast SEO options should be "Good (Green)" and "OK (Yellow)"
<img width="150" alt="Screen Shot 2020-09-10 at 2 10 24 PM" src="https://user-images.githubusercontent.com/3868028/92778681-646ce900-f36f-11ea-8624-4a3bd916edfb.png">

- Let's reorder these items. "Title" should be on top, not "Excerpt"
![Screen Shot 2020-09-10 at 2 10 57 PM](https://user-images.githubusercontent.com/3868028/92779100-c3326280-f36f-11ea-81f4-21720e468255.png)

**Comment by andergmartins** [comment]
@stevejburge please, could you double-check if the following ordering makes more sense?

1. Number of characters in title
1. Number of words in content
1. Number of categories
1. Number of tags
1. Numbers of characters in excerpt
1. Number of internal links in content
1. Number of external links in content
1. Alt text for all images
1. All links use a valid format
1. Featured image
1. Latin characters in permalink

**Comment by stevejburge** [comment]
Yes, except perhaps switching 8 and 9

**Comment by andergmartins** [comment]
Cool tks
