### ISSUE TITLE
Features offered by the plugin don't work while updating the existing post

### ISSUE THREAD

**Issue by manisriv** [publishpress/PublishPress-Checklists#227]
## Expected Behavior
Updating the Existing Post with changes should follow criteria in the checklists plugin 

## Current Behavior
Updating the existing post will no longer follow the criteria in the Checklists plugin

## Steps to Reproduce (for bugs)

1. Navigate to YourDomain.com/wp-admin
2. Login with Admin Credentials
3. Install and activate PublishPress Checklists plugin
4. Go to Checklists (Make sure in settings add to post types posts is checked)
5. Click on the Post Tab(Default selected on Post)
6. Task-Number of characters of title , Select Required from dropdown, who can ignore task -' ', min- 1 and max-5
7. Task-Number of words in content , Select Required from dropdown, who can ignore task -' ', min- 100 and max-250
8. Task-Number of categories , Select Required from dropdown, who can ignore task -' ' , min- 1 and max-3
9. Task-Number of tags , Select Required from dropdown, who can ignore task -' ', min- 1 and max-3
10. Go to Posts, Click on any Existing Post and Change the necessary information less than the criteria mentioned in checklists plugin
11. Click Update on top right corner.

![Update](https://user-images.githubusercontent.com/72168715/94754119-344cb080-0345-11eb-9256-331e0d992377.PNG)

Note: The Plugin fails to operate and the content gets updated

## Environment

* Plugin version : 2.4.0
* Browser Name and version : Google Chrome 85.0.4183.121(64bit)
* Operating System and version (desktop or mobile) : Windows 10 Pro and version 1909
* Xampp version : 7.4.10
* Wordpress version : 5.5.1

**Comment by stevejburge** [comment]
Thanks @manisriv. That's true. This a pre-publishing checklist at the moment.

We do plan to add support for specific statuses (Draft, Pending Review etc) and post-publishing updates
