### ISSUE TITLE
Problem with long permalinks in Classic Editor

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#236]
user report:

> If the length of the slug exceed 34 characters, the Checklist shows Invalid status. If I shortened the slug to 34 character or under, it's all green. This error appears in all posts, not just the linked one.

Confirmed by me:
<img width="1287" alt="Screen Shot 2020-10-27 at 10 57 45 AM" src="https://user-images.githubusercontent.com/3868028/97319622-70d7d300-1843-11eb-9eb5-74aa27700aed.png">

**Comment by richaferry** [comment]
For this issue is it still happening @stevejburge ?
Because im trying in latest version didn't got the issue. I can't reproduce this issue in my side.

**Comment by stevejburge** [comment]
@richaferry Thanks. Let's close this then. It's a very old report.
