### ISSUE TITLE
“All images have alt text” checklist item does not check the featured image

### ISSUE THREAD

**Issue by cbirdsong** [publishpress/PublishPress-Checklists#242]
Enabling “All images have alt text” only checks images inside the body of the post, and does not check and see if the featured image has alt text.

## Expected Behavior

- When “All images have alt text” is enabled featured images are checked for alt text.

## Current Behavior

- Only images in the post content are checked for alt text.

## Steps to Reproduce (for bugs)

1. Enable the “All images have alt text” checklist item.
2. Create a new post and add an image without alt text as the featured image.
3. Try to publish the post.

## Your Environment

* Version used: PublishPress Checklists 2.4.2 on Wordpress 5.6

**Comment by stevejburge** [comment]
Thanks for the detailed report @cbirdsong. Adding ALT Text to Featured Images is a bit more complex than for regular images. Perhaps we can break this out into a new task, alongside others for Featured Images.

**Comment by stevejburge** [comment]
A second request for this today

**Comment by rizaardiyanto1412** [comment]
Received third request: https://wordpress.org/support/topic/require-alt-text-for-featured-image/

**Comment by placoderm** [comment]
Please count me as a fourth request!

I cross post to Mastodon and having alt text there is very important.

Thanks for the great plugin!

**Comment by placoderm** [comment]
Any progress on this? Would love to see this implemented.

**Comment by stevejburge** [comment]
This should be a new setting, I think. It would be confusing to include it in the general “All images have alt text” area.

There can be a new task: "Featured image has ALT text" under here
![Screenshot 2024-01-02 at 11 13 53 AM](https://github.com/publishpress/PublishPress-Checklists/assets/3868028/769f065f-9681-4db9-a3c1-fa4b0cb8c8e8)

**Comment by cbirdsong** [comment]
It might be good to rename the existing item to "Content images have alt text".

**Comment by stevejburge** [comment]
@cbirdsong Yes, good point

**Comment by rizaardiyanto1412** [comment]
This is fixed on 2.11
