### ISSUE TITLE
Anchor links break the valid format requirement in Classic Editor

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#251]
> anchor links inside a post like a href="#anchor" are seen as incorrect, when you enable that check-feature.

- This is the “All links use a valid format” requirement
- Confirmed in Classic Editor

https://wordpress.org/support/topic/anchor-links-are-treated-as-incorrect/

**Comment by rizaardiyanto1412** [comment]
This is solved on this issue: https://github.com/publishpress/PublishPress-Checklists/issues/781
