### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by wotis** [publishpress/PublishPress-Checklists#262]
Hello,
I translated the plugin into German. Here are the files (delete .txt) to use them and include them in the next release:

[publishpress-checklists-de_DE.mo.txt](https://github.com/publishpress/PublishPress-Checklists/files/6252081/publishpress-checklists-de_DE.mo.txt)
[publishpress-checklists-de_DE.po.txt](https://github.com/publishpress/PublishPress-Checklists/files/6252082/publishpress-checklists-de_DE.po.txt)

**Comment by stevejburge** [comment]
awesome, thanks @wotis

**Comment by jfax** [comment]
Hi, any updates on this? Translation from @wotis seems to be great, thanks

**Comment by stevejburge** [comment]
@jfax You can use the files now and this will be included in the next release of Checklists.

**Comment by rizaardiyanto1412** [comment]
The translation files are missing in the Pro version
