### ISSUE TITLE
Optimize plugin for longer post

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Checklists#287]
The plugin slows down the block editor if the post is long. Every character takes a second or two to appear, and if we insert a whole word or a sentence, it takes a few seconds to appear on the screen.

Disabling the plugin fixes the issue.

We probably have an event listener running for every content change, or new char.

>It looks like it struggles with bigger blog posts. I have an outline with about 20 to 30 subheadlines and right now about 1900 words.

**Comment by rizaardiyanto1412** [comment]
I haven't been able to replicate this issue anymore in the latest version of Checklists plugin even with 19,000 words in my editor. I will close this one and reopen if the issue arise again
