### ISSUE TITLE
URL requirement is broken by ellipsis, colon and other characters

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#301]
I can confirm this report: https://wordpress.org/support/topic/latin-characters-in-permalink-required-not-working/#post-14970897

Here's my testing screenshot:
<img width="1343" alt="Screen Shot 2021-10-14 at 3 42 35 PM" src="https://user-images.githubusercontent.com/3868028/137384910-07d5bc6a-6a44-4bbc-88da-e8e35ab7bbf0.png">

**Comment by htmgarcia** [comment]
Only works on classic editor. Reopening to comply with Gutenberg.
