### ISSUE TITLE
Small issue with Review text

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#321]
the review request text for Checklists says "you've been using PublishPress for 1 week."  The button text is customized for the plugin title, but not the main text:
<img width="808" alt="Screen Shot 2021-11-29 at 2 03 21 PM" src="https://user-images.githubusercontent.com/3868028/143927194-51c06ba0-22a5-41bb-a0db-d25fdd3078c8.png">

**Comment by olatechpro** [comment]
@stevejburge this issue seems to be fixed already.

![ppc-review](https://user-images.githubusercontent.com/46832636/148966066-ed450e0a-f087-4305-838d-88ba1f39b3eb.jpg)

**Comment by andergmartins** [comment]
Checklists had an outdated version of the WordPress Reviews library, and that cause the bug. I'm updating that library and it will be available on this release we are working on: 2.7.0.
