### ISSUE TITLE
RAW HTML code in the message when there is no requirement selected for the checklist

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Checklists#330]
If you disable all the requirements for the checklist you will see a message in the metabox which contains a link. But after recent refactoring we escaped HTML chars there. 

![image](https://user-images.githubusercontent.com/407131/153455349-d8d161d5-5bda-4f3b-af02-d0a1522d28fd.png)

Instead of escaping all the message, we should only escape the text that is translateble.

This can be fixed on the file `modules/checklists/templates/meta-box.php`.

**Comment by richaferry** [comment]
Already resolved in this pr https://github.com/publishpress/PublishPress-Checklists/pull/332
