### ISSUE TITLE
"Who can ignore the task" is not saved

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Checklists#331]
![image](https://user-images.githubusercontent.com/407131/153457281-a67dc8ab-0b94-4f81-b29f-5114e1690870.png)

If you select a user role for ignoring that task and save the changes, the page refreshs and the value was not saved.

**Comment by olatechpro** [comment]
**Update**: It seems the checklist settings is not updating at all. Changing any other option doesn't save either. It could be related to permission check and i'm checking that now.

**Comment by richaferry** [comment]
Already resolved in this pr https://github.com/publishpress/PublishPress-Checklists/pull/333
