### ISSUE TITLE
Replace publishpress_checklists_manage_checklist_cap manage_options with manage_checklists

### ISSUE THREAD

**Issue by olatechpro** [publishpress/PublishPress-Checklists#334]
...on the other places where we have the filter `publishpress_checklists_manage_checklist_cap` being applied, lets remove `manage_options` and replace with `manage_checklists`. Then we are able to remove this method:
```
public function checklists_manage_capability($capability)
        {
            return 'manage_checklists';
        }
```

**Comment by richaferry** [comment]
Already resolved in this pr https://github.com/publishpress/PublishPress-Checklists/pull/335
