### ISSUE TITLE
Yoast SEO word count breaks in Pending Review

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#345]
This is an odd bug. Yoast SEO shows a word count of 0, but only in Pending Review status with Checklists enabled

<img width="574" alt="Screen Shot 2022-02-23 at 1 44 37 PM" src="https://user-images.githubusercontent.com/3868028/155386604-f77e4ce7-cf6f-4ffa-b639-fb5f732b9cb8.png">

**Comment by stevejburge** [comment]
We've been able to confirm this with a second user and also my testing:

- Enable Yoast and Publish Press Plugin, add a check rule, for example recommended post_title min 20 max 70.
- Create post, add some text, save as concept, and REFRESH the page.
- Check yoast analyses, it doesn't work, it cannot read the post_content.

**Comment by ojopaul** [comment]
### Note:

I realised this part of the `meta-box.js` is responsible for it issue.

```
// Disable first save button until requirements are meet when "Include pre-publish checklist" is disabled
    // @TODO Figure out how to get the status of "Include pre-publish checklist" and add it to the if() below
    if (PP_Checklists.is_gutenberg_active() && PP_Checklists.is_published() !== true) {
        $(document).on(PP_Checklists.EVENT_TIC, function (event) {
            var has_unchecked_block = $('#pp-checklists-req-box').children('.status-no.pp-checklists-block');
            if (has_unchecked_block.length > 0) {
                wp.data.dispatch( 'core/editor' ).lockPostSaving( 'ppcPublishButton' );
            } else {
                wp.data.dispatch( 'core/editor' ).unlockPostSaving( 'ppcPublishButton' );
            }
        });
    }
```

Running `lockPostSaving` is conflicting with Yoast SEO that rely on the action for on page load metrics.

I'll try and delay the time we load the meta-box.js to see if it'll fix the issue.

**Comment by stevejburge** [comment]
Awesome work, thanks @ojopaul

**Comment by andergmartins** [comment]
Good job @ojopaul that makes sense to me
