### ISSUE TITLE
Missing translation string for "Featured image width between"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#346]
At the moment, it's not possible to translate the "Featured image width between" requirement because it's missing the language string

**Comment by ojopaul** [comment]
@stevejburge The requirement string is `"Featured image width"`(Pro feature) right? Can't find `"Featured image width between"`.

If so, i think we only need to synch the translation pot as the string passed through translation.

**Comment by stevejburge** [comment]
@ojopaul Sorry, yes, that report wasn't quite correct. This is the string:
<img width="1082" alt="Screen Shot 2022-04-11 at 2 58 51 PM" src="https://user-images.githubusercontent.com/3868028/162810457-739fe7a6-2493-4a6f-b4a3-bcb5e2f38036.png">

**Comment by ojopaul** [comment]
@stevejburge here's a confirmation that the strings is available for translation https://github.com/publishpress/PublishPress-Checklists-Pro/blob/2d0ae343eb82dc89013b7e8b3c878728b85ef94c/src/modules/featured-image-size/lib/Requirement/FeaturedImageWidth.php#L44

Now, i'm confused if we should leave the translator to sync the translation pot or i should do it by using a plugin like loco translate and then update it?

**Comment by ojopaul** [comment]
This issue is fixed and merged in Pro
