### ISSUE TITLE
Valid URL check is reporting links with #

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#352]
`I'm using the "valid URLs" check and it is flagging a legitimate in-page anchor link: a href="#footnote". It's probably looking for links beginning with a protocol or a leading slash, but it's flagging the leading "#" (I assume) which is valid for the href attribute of anchor tags.`

We probably need to update /core/Utils/HyperlinkValidator.php

**Comment by ojopaul** [comment]
@stevejburge, i believe you're referring to `"All links use a valid format"` requirement. If so, i traced the code and realised there are two checks for the requirement. The client side check which makes use of javascript and server side php.

So, just to be clear, any url that starts with '#' should be skipped for this requirement right?

**Comment by stevejburge** [comment]
@ojopaul Yes, I think so

Maybe in the future, we can expose the Regex for people to change themselves
