### ISSUE TITLE
Get "Include pre-publish checklist" status

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Checklists#376]
This may help when included in WP core https://github.com/WordPress/gutenberg/issues/34405
![Screen Shot 2022-04-27 at 9 35 46](https://user-images.githubusercontent.com/4999794/165543397-4b5a5a2d-2b49-4393-a575-1688327f7f43.png)

Involved code: https://github.com/publishpress/PublishPress-Checklists/blob/development/modules/checklists/assets/js/meta-box.js#L682-L693

Issue related somehow to #343

**Comment by olatechpro** [comment]
@htmgarcia Can you explain what this issue is all about or what we're looking to achieve? I really don't understand what do do or what to test for on this issue

**Comment by htmgarcia** [comment]
@olatechpro I don't remember the details, but I think is related to the fact that if "Include pre-publish" is disabled, the checklists from PP Checklist requirements are ignored when saving the post (e.g. post must have 2 tags). So we would need a way to detect if "Include pre-publish" is enabled or disabled as a workaround for this issue https://wordpress.org/support/topic/last-update-disables-the-publish-button-2/

**Comment by olatechpro** [comment]
Oh, thanks. I'll test towards that @htmgarcia
