### ISSUE TITLE
Setting Limits in Checklist for Series

### ISSUE THREAD

**Issue by franpiper** [publishpress/PublishPress-Checklists#410]
**Describe the bug**
Testing Min and Max limits for Series in Checklist Plugin

**To Reproduce**
1. Active Plugin PublishPress Checklist
2. In Dashboard, click on Checklist, click on Checklist
3. Set Limits for how many series required or recommended between 2 and 5 
4. Added three New Series 
5. Added three new post assigning series to each posts
6. the checklist for how many series will not allowing me to publish page

**Expected behavior**
I only set the limits to being recommended, expected a warning only

**Screenshots**
![checklist_Limit_settings](https://user-images.githubusercontent.com/108231635/184562981-0317c37d-e938-46e5-a949-8aa06776cbdf.PNG)
![CheckList_Series List](https://user-images.githubusercontent.com/108231635/184562991-4a718a5b-faf0-423b-9215-37d5ae98cba3.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser - chrome
 - Version [103.1.17779.135]

**Additional context**

**Comment by rizaardiyanto1412** [comment]
@franpiper Do you mind explaining what's the issue?

You expect a warning only because you set it to recommended. But that's already a warning. If it's required, there should be an asterisk (*) on the checklist which will prevent you from publish the post. You should be able to publish it even it shows red.

Let me know if I'm missing something in this case

**Comment by franpiper** [comment]
I did tried a couple of times to publish with the warning in red for the
number of recommended series after I set in the limits, however it would
not publish.
I apologize that when I logged out and restarted my WordPress program
everything worked as it should, it may have been something on my end, I
opened a new site and tried to recreate the bug again, and everything
worked as it should.


Fran
