### ISSUE TITLE
Warning: Undefined array key "HTTP_REFERER" in checklists.php

### ISSUE THREAD

**Issue by pcraig3** [publishpress/PublishPress-Checklists#411]
Hi there, we have been using PublishPress checklists pretty successfully but recently ran into a new PHP warning: `Warning: Undefined array key "HTTP_REFERER" in checklists.php`.

<img width="1045" alt="Screen Shot 2022-08-24 at 16 19 49" src="https://user-images.githubusercontent.com/2454380/186530229-20b1a145-5ea7-4677-bc44-97aa6ab43f13.png">

In production, whenever we "save" the checklist rules, we get a blank white screen with nothing at all on it.  We think the problem is that [our AWS setup is dropping the `HTTP_REFERER` field (as described on this SO page)](https://stackoverflow.com/questions/60374755/aws-https-dropping-http-referer), and so [when it gets to the redirect](https://github.com/publishpress/PublishPress-Checklists/blob/1c78f7570a1edc9cb4a7a76e0c2b3d479a07f832/modules/checklists/checklists.php#L1027) in the `save_global_checklist` function, that there's no key there so it fails to load any page at all.

We just want it to return to the same page it was on before, the default PublishPress rules page. Is it possible to encore this logic another way in your plugin to not expect the `HTTP_REFERER` value, or to add a filter maybe so we can pass in a string here? 

We can patch this locally for now but it would be good to do a simple fix here.

**Comment by stevejburge** [comment]
Thanks @pcraig3
