### ISSUE TITLE
Checklist Plugin Bootstrapped Error

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Checklists#417]
Ticket: https://secure.helpscout.net/conversation/2073875657/171614?folderId=2557461

There is an error when installing custom plugin bootstrapped from checklist that are on this guidance: https://publishpress.com/knowledge-base/custom-requirements-plugin/ > https://github.com/publishpress/PublishPress-Checklist-Plugin-Bootstrap

![image](https://user-images.githubusercontent.com/83811723/199662296-9482522d-53fc-4f20-8bd5-cb7b876f6c70.png)

**Comment by rizaardiyanto1412** [comment]
I'm on PHP 7.4, tried with 8.0 and the issue persists.

Installed on fresh WP installation and it shows the same error above. 1 user reported the same issue on WP.org forum

**Comment by andergmartins** [comment]
@rizaardiyanto1412 this can happen if the folder `vendor` is not there.
Please, could you double check you ran `composer update --no-dev` before uploading the bootstrap plugin code? Please, check the instructions on the readme file: https://github.com/publishpress/PublishPress-Checklist-Plugin-Bootstrap#developing
