### ISSUE TITLE
Featured Image Height and Width checks fail for Authors / Contributors

### ISSUE THREAD

**Issue by mgurtzweiler** [publishpress/PublishPress-Checklists#486]
It appears this is a pro feature as i can not find the relevant Requirement / javascript in this repo.

The option appears to use an API call to the `wp/v2/media/<ImageID>` endpoint even if Gutenberg is used. This API call will fail with a 403 for users who do not have permissions to edit others work (except in Authors cases where they uploaded the featured image themselves).

**Comment by olatechpro** [comment]
Fixed

**Comment by olatechpro** [comment]
https://github.com/publishpress/PublishPress-Checklists/issues/523
