### ISSUE TITLE
PublishPress Checklists after install not showing admin menu bar

### ISSUE THREAD

**Issue by vishalgiasoft009** [publishpress/PublishPress-Checklists#503]
PublishPress Checklists after install not showing admin menu bar
![Screenshot_57](https://github.com/publishpress/PublishPress-Checklists/assets/126851786/a62fc22c-77cb-4959-8091-544804fddc9c)

**Comment by stevejburge** [comment]
@vishalgiasoft009 Thanks for reporting this.

This is likely a plugin conflict. Please test and let us know if disabling other plugins can help

**Comment by vishalgiasoft009** [comment]
I have deactivated plugins one by one but the issue is not fixed

**Comment by stevejburge** [comment]
Hi @vishalgiasoft009. This area is for bug reports that can be re-created on other sites. We can't see this issue in our testing

Please keep troubleshooting this issue. Try a different site. Try a different PHP version.

**Comment by stevejburge** [comment]
I see this quite regularly when testing the plugin

**Comment by olatechpro** [comment]
This is related to https://github.com/publishpress/PublishPress-Checklists/issues/524 and will be fixed on that
