### ISSUE TITLE
Disable Checklists on Page Builder

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Checklists#504]
Step to replicate:
1. Install Yoast, Woocommerce, PP Checklist
2. Go to Checklist > Enable checklist for word count
3. Create new product
4. Edit with elementor
5. Add few contents
6. Go back, observe issue, the checklist still crossed

![image](https://github.com/publishpress/PublishPress-Checklists/assets/83811723/726c9506-6f9a-422c-9fba-cc2f7a574bc6)

**Comment by vaibhavshukla3110** [comment]
Hi, Is there any update regarding this issue?

**Comment by rizaardiyanto1412** [comment]
@vaibhavshukla3110 We will fix this issue in the next release.

**Comment by rizaardiyanto1412** [comment]
I think related to this one: https://github.com/publishpress/PublishPress-Checklists/issues/534

**Comment by olatechpro** [comment]
From : https://github.com/publishpress/PublishPress-Checklists/issues/534

> Currently the checklist requirement can be bypass if the user using Elementor. It should be good if our checklist also affecting Elementor
> 
> Original request: https://secure.helpscout.net/conversation/2391821178/211662?folderId=6932143
