### ISSUE TITLE
Setting for Taxonomies

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#560]
Can we add a "Taxonomies available for Checklists" setting?

If a taxonomy is checked, it appears on the Checklists admin screen

**Comment by richaferry** [comment]
Hi @stevejburge ,
So for this task want to capabilities modify taxonomies available for checklists settings screen right?

**Comment by stevejburge** [comment]
@richaferry I think we can skip this now that https://github.com/publishpress/PublishPress-Checklists/issues/732 is fixed
