### ISSUE TITLE
Extra "Save Changes" button

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#563]
Could we make the "Save Changes" button easier to find? Perhaps add a new one at the top, as in Capabilities?

![Screenshot 2023-12-04 at 8 42 22 AM](https://github.com/publishpress/PublishPress-Checklists/assets/3868028/e87a6365-e4e6-4cb1-9de4-56a104fcf6da)

**Comment by olatechpro** [comment]
@stevejburge This should be added on Capabilities repository :)

**Comment by stevejburge** [comment]
Sorry, this applies to the main "Checklists" screen
![Screenshot 2024-01-04 at 5 50 49 PM](https://github.com/publishpress/PublishPress-Checklists/assets/3868028/9578b5a0-2e3c-42d3-976c-0726cc6a6783)

**Comment by olatechpro** [comment]
Oh, I was only looking at the capabilities picture
