### ISSUE TITLE
PHP notice with PHP 7.4

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#565]
![Screenshot 2023-12-07 at 8 51 43 AM](https://github.com/publishpress/PublishPress-Checklists/assets/3868028/ebba9c24-47c2-428b-87dc-c3c98537ca63)
![Screenshot 2023-12-07 at 9 08 10 AM](https://github.com/publishpress/PublishPress-Checklists/assets/3868028/3f4942cc-d274-4c73-a435-e89cd6b89303)

**Comment by olatechpro** [comment]
Fixed
