### ISSUE TITLE
Required and prohibited tags freeze webpage because of dropdown

### ISSUE THREAD

**Issue by coenve** [publishpress/PublishPress-Checklists#637]
PublishPress got the option to set required or prohibited tags in a recent version of the plugin. To set these tags you use a dropdown list with ALL the tags. We run websites with 14k and 27k tags. Loading those in a dropdown list (twice) causes the webpage to freeze up. 

Can you adjust this to a search bar for the tags? Or an option to disable the required and prohibited tags option in your plugin?

**Comment by stevejburge** [comment]
Thanks for reporting this @coenve. Is the issue on the main "Checklists" screen?
