### ISSUE TITLE
Redirect to Checklists screen on new activation 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#669]
https://make.wordpress.org/core/2024/05/24/wordpress-6-5-4-an-upcoming-maintenance-release/

We should redirect new users to the "Checklists" screen

**Comment by olatechpro** [comment]
@stevejburge This should only be added to wordpress version 6.5.4 and above?

**Comment by stevejburge** [comment]
@olatechpro I think it can apply to all versions, please

**Comment by rizaardiyanto1412** [comment]
@olatechpro I would love to check this. Thanks Ola for the information about Taxopress. 
I will check this next week after I finish this task https://github.com/publishpress/PublishPress-Checklists/issues/559. Is that okay?

**Comment by olatechpro** [comment]
Sure, that make sense @rizaardiyanto1412
