### ISSUE TITLE
Small text changes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#686]
Old: If the "Status" option is enabled, it can be used to avoid using the Checklists requirements.
New: Disabling the "Status" option is recommended because it can be used to avoid using the Checklists requirements.

Old: Disable quick edit completely except user who has "manage_capability".
New: This will disable "Quick Edit" for all users except those with the "manage_options" capability.

**Comment by rizaardiyanto1412** [comment]
Sorry Steve. That's definitely typo there. I was trying to say manage_options

**Comment by rizaardiyanto1412** [comment]
What's the best way to handle this one? Should I open new PR or @richaferry will correct it? or else?

**Comment by stevejburge** [comment]
@rizaardiyanto1412 @richaferry you guys can decide between yourselves :)

**Comment by richaferry** [comment]
> What's the best way to handle this one? Should I open new PR or @richaferry will correct it? or else?

for this case i think your PR will merge into release branch. not into development branch. because this case i think need treat as hotfix.

**Comment by richaferry** [comment]
Already closed in this PR #687
