### ISSUE TITLE
Quick Edit settings disabled by default

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#689]
- These Quick Edit boxes should not be checked by default

![Screenshot 2024-07-16 at 10 54 33 AM](https://github.com/user-attachments/assets/6053db19-b379-4467-a231-f8c805cd631c)

**Comment by richaferry** [comment]
Already fix in this pr https://github.com/publishpress/PublishPress-Checklists/pull/690
