### ISSUE TITLE
Compatibility with WordPress 6.6

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Checklists#697]
Step to replicate: 

1. Add new checklist requirement
2. Edit existing post
3. Try to Update or Publish the post and nothing happen, the page just stay the same while there's an error in console pointing to the method
4. Or try to add new category, it will not be possible

![image](https://github.com/user-attachments/assets/68f82002-d006-4432-b45d-60f517150e2a)

**Comment by rupert-quaderer** [comment]
Same error on my page.

**Comment by olatechpro** [comment]
Thanks @rupert-quaderer We're working to get a release out for this today.
