### ISSUE TITLE
Add option to disable publish button

### ISSUE THREAD

**Issue by james-tyner** [publishpress/PublishPress-Checklists#728]
## Expected Behavior
In version 2.8.0 of PublishPress Checklists Pro, users are not allowed to click "Publish" on a post if required checklist tasks are not completed. Once they arrive at the "pre-publish checks" screen, the Publish button is grayed out until all checklist requirements are met.

## Current Behavior
In version 2.12.0 of PublishPress Checklists Pro, nothing prevents users from clicking Publish, even if the checklist is not fulfilled. Instead, after clicking, the story fails to publish and users are shown a red error banner saying required checklist items must be completed before publishing.

## Possible Solution
Restore disabled Publish button behavior, or at least make it an option in the plugin settings.

## Context
I understand that some changes were made related to #567 to reduce conflicts with other plugins, and I'm guessing that's what led to the removal of interactions between PublishPress Checklists and the Publish button. But is there really nothing that can be done to maintain the old behavior? It was an elegant way to signal to users that there were pending tasks they needed to complete. The new behavior may lead to confusion among users who believe their story has published and don't notice the error message.

## Your Environment

* Version used: WordPress 6.6.1
* Browser Name and version: Chrome 127
* Operating System and version (desktop or mobile): macOS 14.6

**Comment by stevejburge** [comment]
Hi @james-tyner. Thanks for using Checklists Pro. Can you open a support ticket? We'll dig into this for you
