### ISSUE TITLE
PHP errors in plugin settings when Yoast 23.4 is enabled

### ISSUE THREAD

**Issue by tedw** [publishpress/PublishPress-Checklists#751]
## Expected Behavior

No PHP errors in admin

## Current Behavior

I get the following errors on the Checklists page (`/wp-admin/admin.php?page=ppch-checklists`):

<img width="1438" alt="SCR-20240904-moax" src="https://github.com/user-attachments/assets/c0f7296e-cd5f-4fa2-8598-f0b65ddfc473">

## Possible Solution

The warnings go away when I disable Yoast, but I need to use it so not a solution.

## Steps to Reproduce (for bugs)

Install and activate Yoast 23.4 then go to `/wp-admin/admin.php?page=ppch-checklists`

## Context

Thanks for looking into this!

## Your Environment

PHP 8.2, WP 6.6.1, plugin version 2.13.0

**Comment by rizaardiyanto1412** [comment]
Fixed here: https://github.com/publishpress/PublishPress-Checklists/pull/754

**Comment by tedw** [comment]
@rizaardiyanto1412 Thanks for the quick fix!
