### ISSUE TITLE
Can we hide ACF and WooCommerce areas when not used?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#756]
We have ACF and WooCommerce tabs on the "Posts" screen, for example
![Screenshot 2024-09-16 at 10 19 49 AM](https://github.com/user-attachments/assets/10726edc-ca89-4fb7-b412-4232571ba6b2)

**Comment by richaferry** [comment]
Already fix. Can be retest in this version 2.14.0-beta.1-ACF.2
