### ISSUE TITLE
Fatal error with new image count feature

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#767]
If you enable the new Alt text minimum and maximum feature, it's not possible to create a new post:
![Screenshot 2024-09-23 at 9 39 04 AM](https://github.com/user-attachments/assets/a157f0b4-a64a-4f43-9710-13701bf57ed5)

**Comment by richaferry** [comment]
Already resolve in this PR https://github.com/publishpress/PublishPress-Checklists-Pro/pull/75
