### ISSUE TITLE
Custom arrow is in the wrong place

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#778]
This arrow removes the whole custom task, but it appears inside the role box. 

In fact, I don't think it works. It's not possible to remove the custom item.
![Screenshot 2024-09-25 at 9 42 57 AM](https://github.com/user-attachments/assets/a04c41d1-d2f5-4c69-97f6-eb44feaf9709)

**Comment by stevejburge** [comment]
Sorry, still seeing this in the box
![Screenshot 2024-10-11 at 10 31 42 AM](https://github.com/user-attachments/assets/82c6545f-0e1c-4675-b903-b857b5bc8ffa)

**Comment by richaferry** [comment]
Sorry @stevejburge , for this remove icon should be outside the box?

**Comment by stevejburge** [comment]
Yes, please. We use this X to delete the whole row, not just that box.

**Comment by richaferry** [comment]
Ah i see. Ok then steve. Will do.
