### ISSUE TITLE
Update the plugin description

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#780]
Old: Add support for checklists in WordPress
New: With PublishPress Checklists, you can choose publishing requirements for your content.
![Screenshot 2024-09-25 at 10 21 04 AM](https://github.com/user-attachments/assets/21cd99c9-0f15-45e7-a5e1-32efdbc9c7de)

**Comment by stevejburge** [comment]
Sorry, still seeing the old one

**Comment by richaferry** [comment]
For this issue is it still seeing the old one? @stevejburge 
Because in my side already changes into the new one. 
![image](https://github.com/user-attachments/assets/ff01076b-00ca-423d-a117-82072c243695)

**Comment by stevejburge** [comment]
@richaferry I think it's fixed in the Free version but not Pro

**Comment by richaferry** [comment]
Ah pro version. I think i missed update for pro version. Will update in next commit @stevejburge
