### ISSUE TITLE
"Required Categories" and "Prohibited Categories" showing deleted terms

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#786]
The "Required Categories" and "Prohibited Categories" and pulling the wrong data.

These Categories were deleted:
![Screenshot 2024-10-03 at 11 45 35 AM](https://github.com/user-attachments/assets/24677de2-1fac-4ece-9965-42f9ae14e769)

**Comment by richaferry** [comment]
This issue cause we are implementing cache. currently we put 10 mins caching mechanism. because if the site has huge category will freeze that page. For this solution i will decrease cache expiry into 1 minute. @stevejburge

**Comment by stevejburge** [comment]
Sounds good, thanks @richaferry
