### ISSUE TITLE
"Required Tags" and "Prohibited Tags" is pulling wrong data

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#787]
Related: https://github.com/publishpress/PublishPress-Checklists/issues/786

This seems to be showing Categories, not Tags:
![Screenshot 2024-10-03 at 11 48 13 AM](https://github.com/user-attachments/assets/8662217c-23b2-444e-b4ec-9eb3bc9f196a)

**Comment by richaferry** [comment]
This issue cause we are implementing cache. currently we put 10 mins caching mechanism. because if the site has huge category will freeze that page. For this solution i will decrease cache expiry into 1 minute. @stevejburge

**Comment by richaferry** [comment]
I can't replicate this issue in my side. Is it still issue in your side @stevejburge ?

**Comment by stevejburge** [comment]
@richaferry I can't. Let's close this for now
