### ISSUE TITLE
Conflict with Rankmath

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Checklists#791]
Hi. The issue occurs when setting an exact category number while having RankMath’s “Primary Taxonomy” feature enabled (set to category (default) under RankMath > Titles & Metas > Post Types > Posts), using the classic editor. Gutenberg appears to be unaffected.

Posts will load fine, but any change to the categories will cause the category count item on the checklist to invalidate. It does not validate again until the page is reloaded/draft saved. This is true whether it’s set to recommended or required. Just setting the minimum or maximum has no issue.

var obj = $('#categorychecklist input:checked');
That line (1103 in meta-box.js), when evaluated in the console with a single category selected (whether from the DB or after live changes) returns a length of 2 with primary taxonomy enabled and a length of 1 with it disabled. Again, it only occurs on exact (min 1, max 1 in my case). The existence/use of parent and children categories makes no difference.

I’ve been experiencing this issue for quite some time. I ended up just disabling Checklists and going to a different plugin without digging too far into it. Now, I have a use case for the PublishPress Pro bundle, so I dug in. I was having the issue before switching from Yoast Pro to RankMath, which also has a primary category feature, but I did not note the versions before deleting Yoast (I made the switch about 1 month ago).

Versions --
PHP: 8.1-8.3
WordPress: 6.6-6.6.2
Checklists: 2.14.0
RankMath/Pro: 1.0.229/3.0.72

Original report: https://wordpress.org/support/topic/conflict-with-min-max-categories-and-rankmaths-primary-catgeory-feature/

**Comment by brysont** [comment]
OP here, in case any additional info/steps are needed. Thanks Riza.
