### ISSUE TITLE
Wrong result openAI checklists

### ISSUE THREAD

**Issue by vitamarc** [publishpress/PublishPress-Checklists#823]
## Expected Behavior

The answer 'No' for the OpenAl prompt task, 'Is this content tone friendly?', should be marked in red and display that the task has not been completed.
## Current Behavior

The response says 'Content is not friendly' or something like that but it is marked in green and displays the answer 'Yes"
## Steps to Reproduce (for bugs)

1.  Open checklist -> Custom
2.  Add OpenAl prompt task 'Is this content tone friendly?' enable and save it
3. Open Posts-> Add new post
4.  Enter text in an aggressive tone something like 'Writing something makes no sense because you know what has happened already. This is your only mistake causing so much damage you couldn't imagine.'
5. Click 'Check now' button
6. Click 'See the full response'
7. It says 'Yes: No' and describes what exactly wasn't friendly
![Al_Is_this_content_frendly](https://github.com/user-attachments/assets/013217f1-8245-4fe9-8af4-95d5efdfc158)
![Al_Is_this_content_frendly2](https://github.com/user-attachments/assets/89443445-f571-4c07-b1ec-e03943df8b3a)

## Your Environment

* Version used: Version 2.15.0
* Browser Name and version: Google Chrome Version 130.0.6723.59
* Operating System and version (desktop or mobile): Windows 11 Home
* Link to your project:

**Comment by stevejburge** [comment]
Thanks @vitamarc

**Comment by vitamarc** [comment]
Thank you for API key to test it
