### ISSUE TITLE
Check for Yoast SEO meta desc and focus keyword

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Checklists#86]
In your upcoming features you're mentioning [some ideas](https://pressshack.com/addons/content-checklist/) for the Content Checklist, of which some for Yoast SEO. I hope you'll consider adding two requirements which are already available in the plugin [Requirements Checklist](https://wordpress.org/plugins/post-type-requirements-checklist/#developers) which we currently use:

* [ ] Require Meta Description
* [ ] Require Focus Keyword

![screen-shot-2017-09-22-12-29-11](https://user-images.githubusercontent.com/478156/30740729-72efb9fa-9f92-11e7-98cf-83c75803ff14.png)

Also; I hope the 'Get the green checkmark for Yoast SEO' is optional, since even team Yoast state it's [not always worth pursuing](https://yoast.com/want-green-bullet-wp-seo/).

I really like the other feature ideas and look forward to their implementation.

**Comment by stevejburge** [comment]
Maybe let's allow Yoast SEO to do the work for us and we just check to see if these 2 scores are green:
<img width="290" alt="Screen Shot 2020-07-09 at 6 41 33 PM" src="https://user-images.githubusercontent.com/3868028/87097906-2ab71f00-c214-11ea-9826-ee8e9ce6f172.png">
